name = "DotProductIO"
uuid = "1f956d4d-7fc4-4553-81e4-504258e7585a"
version = "0.1.0"
authors = ["Roy Chih Chung Wang <roy.c.c.wang@proton.me>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.12.0"
julia = "1.12.1"

[apps.dp-app]
